services:

  backend:
    build: ./backend
    container_name: lib_back

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/bibliotheque

    depends_on:
      db:
        condition: service_healthy

    volumes:
      - ./backend:/app

  db:
    image: postgres:16
    container_name: bibliotheque_db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bibliotheque

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: